apiVersion: 1

datasources:
  - name: ClickHouse
    uid: clickhouse
    type: vertamedia-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    database: logs
    basicAuth: false
    isDefault: true
    jsonData:
      defaultDatabase: logs
      usePOST: false
    editable: false

