apiVersion: 1

datasources:
  - name: ClickHouse
    uid: clickhouse
    type: vertamedia-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    basicAuth: false
    isDefault: true
    jsonData:
      defaultDatabase: logs
      usePOST: false
      port: 8123
      server: clickhouse
    editable: false

